package com.example.chat.event;

public enum ChatEventType {
    CONVERSATION_STARTED,
    CONVERSATION_QUEUED,
    CONVERSATION_ASSIGNED,
    CONVERSATION_ACCEPTED,
    MESSAGE_RECEIVED,
    MESSAGE_DELIVERED,
    CONVERSATION_CLOSED,
    PRESENCE_UPDATED
}

